### ISSUE TITLE
Recommended Data Attributes to Facilitate Patient Matching

### ISSUE THREAD

**Issue by jsnichols** [standardhealth/shr#76]
I began to draft a list of data elements that I thought would be most useful to facilitate patient matching. Then it occurred to me that someone else has already done this. Here's a [suitable list](http://perspectives.ahima.org/wp-content/uploads/2014/12/PatientMatchingAppendixA.pdf) which appears thorough, is well-referenced, and follow closely fields we have already added to SHR.

This list is from a helpful white paper [Patient Matching in Health Information Exchanges](
http://perspectives.ahima.org/patient-matching-in-health-information-exchanges/). 

The paper describes several current problems that are mitigated by the SHR: 
>Lack of a standard data set can lead to patient records not being linked to one another in the HIE, resulting in an incomplete health record being available to the provider for the patient being treated, thereby defeating the purpose of the HIE.
>
>Currently, organizations are matching patient records within their own system but face challenges in incorporating patient matching techniques across care settings and different EHR systems.
>
>For [health data interoperability] to be successful, standards for data capture, definitions, and [formatting](http://perspectives.ahima.org/wp-content/uploads/2014/12/PatientMatchingAppendixB.pdf) must be developed to allow an electronic system to accurately identify patients across disparate EHR systems.
>
>The adoption of a nationwide patient matching strategy that **standardizes a set of patient demographic elements stored in a standard format** would support existing models of patient matching such as the federated identity knowledge discovery model and the centralized identity knowledge approach.

**I recommend that SHR adopt [this list](http://perspectives.ahima.org/wp-content/uploads/2014/12/PatientMatchingAppendixA.pdf) of demographic measures in its initial approach to patient matching, with the addition of a patient photograph as a secondary requirement.**

**I recommend that we closely monitor efforts such as the [CHIME National Patient ID Challenge](https://herox.com/PatientIDChallenge/resources), the [NATE BB4C Trust Bundle](http://nate-trust.org/nbb4c-trust-bundle/) and the movement for a [national patient identifier](http://www.cio.com/article/2972266/healthcare/national-patient-identifier-struggles-for-life.html) so that future iterations of SHR can nimbly adapt to emerging best practices in the field.**

**Comment by markkramerus** [comment]
Great!  I added a tab (named "matching") that covers matching, linking the fields in the AHMIA report to entry types in the SHR. We have all of them covered, plus several more (including photograph).

**Comment by susanhaas** [comment]
Like using pre-existing standards.
Reviewing this in detail demonstrates a few areas that aren't fully "settled".   Examples:
  death info only references VA as a source
  situation of 2 (or more) middle names not addressed
  country of birth but not city if not US--not good enough for people from populous countries
  lacks info about father (vs mother's 'maiden name')
Finally, I'm not sure we're including in our thought processes the millions of people who don't have documents or don't know their birthdates, etc.  What special provisions for identification do we need to consider for them?  Not sure where to look but Kathy Lewis might have leads.
